#!/bin/sh

# install Portmaster
function Portmaster(){
	# Clone the repository
	git clone https://github.com/safing/portmaster-packaging

	# Enter the repo and build/install the package (it's under linux/)
	cd portmaster-packaging/linux
	makepkg -is

	# Start the Portmaster and enable autostart
	sudo systemctl daemon-reload
	sudo systemctl enable --now portmaster
}

# install Dash
function Dash(){
	sudo pacman --noconfirm --needed -S dash
	sudo rm -rf /bin/sh && sudo ln -sf /usr/bin/dash /bin/sh
}

# vim plug
function VimPlug(){
	# vim
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	
	# nvim
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
	       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
}

# grub minimal theme
function Grub_Theme(){
    git clone https://github.com/tomdewildt/minimal-grub-theme.git /tmp/minimal && cd /tmp/minimal
    make install
}

# starship prompt
function starship(){
    curl -sS https://starship.rs/install.sh | sh
    [[ -z $(grep "eval \"\$(starship init bash)\"" ~/.bashrc)  ]] && echo -e "# starship prompt\neval \"\$(starship init bash)\""
}

function main(){
    if [[ "-i" == "${@}"  ]]; then
        cmd=${@}
    else
        cmd=$(grep "^function" ${0}|grep -v "^function main"|awk '{print $2}'|cut -d\( -f1|fzf -m --prompt "Install")
    fi

    for run in ${cmd}; do
		${run}
	done
}
main

